# ./app.php/dkp will be handled by class sajaki.bbdkp.controller and method(), passing name as argument.
sajaki_bbdkp_controller:
    path: /dkp/{name}
    defaults: { _controller: sajaki.bbdkp.controller:handle }
