#bbdkp 2.0 urls
#
#valid_views = array('news', 'roster', 'standings', 'loothistory', 'lootdb',
#'listevents', 'stats', 'listraids', 'event',
#'item', 'raid', 'member', 'bossprogress', 'planner');
#
# default route
#dkp
bbdkp_00:
    path: /dkp
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1    }
    requirements:
     guild_id: \d*
#dkp.php?page=standings
#dkp.php?page=standings&guild_id=1
#dkp/standings/1
bbdkp_01:
    path: /dkp/standings
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1    }
    requirements:
     guild_id: \d*
#dkp.php?page=standings
#dkp.php?page=standings&guild_id=1
#dkp/standings/1
bbdkp_01a:
    path: /dkp/standings/guild/{guild_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1    }
    requirements:
     guild_id: \d*
#dkp.php?page=news&guild_id=1
#dkp/news/guild/1
bbdkp_02:
    path: /dkp/news/guild/{guild_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1    }
    requirements:
     guild_id: \d*
#dkp.php?page=roster&guild_id=1&rosterlayout=0
#dkp/roster/guild/1
#dkp/roster/guild/1?rosterlayout=1
bbdkp_03:
    path: /dkp/roster/guild/{guild_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1 }
    requirements:
     guild_id: \d*
#dkp.php?page=member&member_id=2&dkpsys_id=3
#dkp/member/2?dkpsys_id=3
bbdkp_04:
    path: /dkp/member/{member_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleMember, member_id: 1 }
    requirements:
     member_id: \d*
#dkp.php?page=stats&guild_id=1
#dkp/stats/guild/1
bbdkp_05:
    path: /dkp/stats/guild/{guild_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1 }
    requirements:
     guild_id:  \d*
#dkp.php?page=listevents&guild_id=1
#dkp/listevents/guild/1
bbdkp_06:
    path: /dkp/listevents/guild/{guild_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1 }
    requirements:
     guild_id:  \d*
#dkp.php?page=listraids&guild_id=1
#dkp/listraids/guild/1
bbdkp_07:
    path: /dkp/listraids/{guild_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1 }
    requirements:
     guild_id:  \d*
#dkp.php?page=raid&raid_id=1&guild_id=1
#dkp/raid/1
bbdkp_08:
    path: /dkp/raid/{raid_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleRaid, raid_id: 1 }
    requirements:
     raid_id:  \d*
#dkp.php?page=loothistory&guild_id=1
#dkp/loothistory/guild/1
bbdkp_09:
    path: /dkp/loothistory/guild/{guild_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1 }
    requirements:
     guild_id:  \d*
#dkp.php?page=lootdb&guild_id=1
#dkp/lootdb/guild/1
bbdkp_10:
    path: /dkp/lootdb/guild/{guild_id}
    defaults: { _controller: sajaki.bbdkp.controller:handleGuild, guild_id: 1 }
    requirements:
     guild_id:  \d*
#portal.php/guild/1
bbdkp_43:
    path: /dkpportal/guild/{guild_id}
    defaults: { _controller: sajaki.bbdkp.portalcontroller:handlePortal, guild_id: 1 }
