# mapping of service "sajaki.bbguild.controller" to class sajaki\bbguild\controller\main
services:
    sajaki.bbguild.controller:
        class: sajaki\bbguild\controller\main
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
    sajaki.bbguild.portalcontroller:
        class: sajaki\bbguild\controller\main
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
    sajaki.bbguild.listener:
        class: sajaki\bbguild\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @user
            - @config
        tags:
            - { name: event.listener }
