# mapping of service "sajaki.bbdkp.controller" to class sajaki\bbdkp\controller\main
# mapping of service "sajaki.bbdkp.listener" to class sajaki\bbdkp\event\main_listener
services:
    sajaki.bbdkp.controller:
        class: sajaki\bbdkp\controller\main
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
    sajaki.bbdkp.listener:
        class: sajaki\bbdkp\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @user
            - @config
        tags:
            - { name: event.listener }