# mapping of service "sajaki.bbguild.controller" to class sajaki\bbguild\controller\main
services:
    bbdkp.bbguild.controller:
        class: bbdkp\bbguild\controller\main
        arguments:
            - '@config'
            - '@config_text'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
    bbdkp.bbguild.portalcontroller:
        class: bbdkp\bbguild\controller\main
        arguments:
            - '@config'
            - '@config_text'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
    bbdkp.bbguild.listener:
        class: bbdkp\bbguild\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@config'
        tags:
            - { name: event.listener }
